# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1416655070dc4fb17c93e67b66f985e437576fa0591a63cd0558df629460eb3c9bc5fa9043528e388897890ebe6c25dcac07fc4ddc39d0470da2261285cc9b8

test:
  secret_key_base: 40df3e92d676faed769dd18489f8bdc873051b6247b52ad444123888cd2251cc9d1dd9ef1067f1002019d19e0b0fe22d33f89e3ae31cffbd48458936076347d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
